### ISSUE TITLE
Question regarding Control plane app

### ISSUE THREAD

**Issue by Mandorath** [COMSYS/pie-for-tofino#1]
I'm trying to setup a test environment that will use the control plane variant you created. However when I compile the program using:

```bash
g++ -Wall -v -I /bf-sde-9.2.0/install/include/  /brft_cpp/src/run_controlplane_pie.cpp  -o control_plane_pie -lpthread
```
The following error is returned:

```bash
/tmp/cc4fbi0n.o: In function `bfrt::run_controlplane_pie::init()':
run_controlplane_pie.cpp:(.text+0x131): undefined reference to `bfrt::BfRtDevMgr::getInstance()'
run_controlplane_pie.cpp:(.text+0x182): undefined reference to `bfrt::BfRtDevMgr::bfRtInfoGet(int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bfrt::BfRtInfo const**) const'
run_controlplane_pie.cpp:(.text+0x1ce): undefined reference to `bfrt::BfRtSession::sessionCreate()'
/tmp/cc4fbi0n.o: In function `main':
run_controlplane_pie.cpp:(.text+0x1d3d): undefined reference to `bf_switchd_lib_init(bf_switchd_context_s*)'
collect2: error: ld returned 1 exit status
```
I usually don't program in c++, so I might be missing something obvious.

I'm using the 9.2.0 SDE version

**Comment by ike-kunze** [comment]
Hi @Mandorath,

we have used a cmake build infrastructure for compiling the controlplane variant and I am thus not entirely sure which g++ call would do the trick (I also don't use C++ that often).
I have thus added a couple of cmake-related files that you can find here #2.
After building the controlplane (using 'cmake .' and 'make'), make sure that you run the controlplane using the run.sh script as you require sudo privileges for executing parts of the controlplane and the run.sh script handles setting up the library paths for you (you can of course also do that manually).
Please let me know if it works using those additional files so that I can then merge them into the main branch, thanks!

Cheers,
Ike

**Comment by Mandorath** [comment]
Hi @ike-kunze,

Yes that did the trick :). I can create a working control plane this way, thank you!

BR,
Maurice
